#!/usr/bin/env python3
"""
Baseline PyTorch LSTM Training Script for Validating Universal AI-Ready Datasets.

This script demonstrates how to ingest the Parquet files generated by the 
`batch_universal_digitizer.py` and feed them into an AI model.

KEY FEATURE: It uses the `confidence` column generated during the Viterbi Graph Extraction 
to demonstrate how to ingest and train models on the universal datasets.
"""
import os
from pathlib import Path
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

class GraphTimeSeriesDataset(Dataset):
    def __init__(self, data_dir: Path, variable: str, resolution: str, seq_len: int = 60, pred_len: int = 12):
        """
        Args:
            data_dir: Root directory of the universal datasets (e.g., output/universal_datasets)
            variable: 'temp', 'humidity', 'precip', 'pressure'
            resolution: '1S', '1T', '1H'
            seq_len: Historical window to observe (e.g., 60 minutes)
            pred_len: Future window to predict (e.g., 12 minutes)
        """
        self.seq_len = seq_len
        self.pred_len = pred_len
        
        target_dir = data_dir / variable / resolution
        if not target_dir.exists():
            raise FileNotFoundError(f"No ML data found at {target_dir}. Did batch_universal_digitizer finish?")
            
        print(f"Loading {variable} data from {target_dir}...")
        parquet_files = list(target_dir.glob("*.parquet"))
        dfs = [pd.read_parquet(f) for f in parquet_files]
        self.df = pd.concat(dfs, ignore_index=True).sort_values("timestamp").reset_index(drop=True)
        
        # 1. Normalize Value (-1 to 1) for Neural Networks
        self.val_min = self.df['value'].min()
        self.val_max = self.df['value'].max()
        self.df['norm_val'] = (self.df['value'] - self.val_min) / (self.val_max - self.val_min) * 2 - 1
        
        self.values = self.df['norm_val'].values
        
        # Total valid sliding windows
        self.length = len(self.df) - self.seq_len - self.pred_len
        print(f"Loaded {len(self.df)} continuous rows. Prepared {self.length} sliding AI windows.")

    def __len__(self):
        return max(0, self.length)

    def __getitem__(self, idx):
        # Input History (X)
        x = self.values[idx : idx + self.seq_len]
        
        # Target Future (Y)
        y = self.values[idx + self.seq_len : idx + self.seq_len + self.pred_len]
        
        return (
            torch.tensor(x, dtype=torch.float32).unsqueeze(-1),
            torch.tensor(y, dtype=torch.float32)
        )

class ClimateLSTM(nn.Module):
    def __init__(self, input_size=1, hidden_size=64, num_layers=2, output_size=12):
        super(ClimateLSTM, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        # x shape: (batch, seq_len, features)
        out, _ = self.lstm(x)
        out = self.fc(out[:, -1, :]) # Take the last hidden state
        return out

def train_baseline_model():
    # Device Setup: Use M4 Pro GPU (MPS) if available, else CPU
    if torch.backends.mps.is_available():
        device = torch.device("mps")
        print("🚀 Utilizing M4 Pro GPU (MPS) for training.")
    elif torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")
        print("⚠️ MPS/CUDA not found. Falling back to CPU.")
        
    try:
        dataset = GraphTimeSeriesDataset(data_dir, variable, resolution, seq_len, pred_len)
    except FileNotFoundError as e:
        print(f"Error: {e}")
        return
        
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    
    model = ClimateLSTM(input_size=1, hidden_size=64, num_layers=2, output_size=pred_len).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    
    loss_fn = nn.MSELoss()

    print(f"\nStarting AI Training for {variable}...")
    model.train()
    for epoch in range(epochs):
        epoch_loss = 0.0
        for i, (X, Y) in enumerate(dataloader):
            X, Y = X.to(device), Y.to(device)
            
            optimizer.zero_grad()
            predictions = model(X)
            loss = loss_fn(predictions, Y)
            
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
            
            if i % 50 == 0:
                print(f"Epoch [{epoch+1}/{epochs}], Step [{i}/{len(dataloader)}], Loss: {loss.item():.4f}")
                
        avg_loss = epoch_loss/len(dataloader)
        print(f"✅ Epoch {epoch+1} Completed. Avg Loss: {avg_loss:.4f}")

    # Save the trained model
    save_path = Path("output/models")
    save_path.mkdir(parents=True, exist_ok=True)
    torch.save(model.state_dict(), save_path / f"lstm_{variable}_{resolution}.pth")
    print(f"\n🏆 Model saved to {save_path}/lstm_{variable}_{resolution}.pth")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--variable", type=str, default="temp")
    parser.add_argument("--res", type=str, default="1H")
    args = parser.parse_args()
    
    train_baseline_model(variable=args.variable, resolution=args.res)
